---
deployment:
  tasks:
    - export DEPLOYPATH=/home/puzo3938/pokenbowl.be/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name '.well-known' -exec /bin/rm -rf {} +
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R .output $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp vite.config.ts $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    - /bin/cat > $DEPLOYPATH/server.js <<'EOF'
import "./.output/server/index.mjs";
EOF
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /usr/bin/touch $DEPLOYPATH/tmp/restart.txt
# O2Switch production deployment trigger.
