/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as SurMesureRouteImport } from './routes/sur-mesure'
import { Route as AdminStocksRouteImport } from './routes/admin/stocks'
import { Route as ApiMollieWebhookRouteImport } from './routes/api/mollie-webhook'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as OrderSuccessRouteImport } from './routes/order.success'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as TrackTokenRouteImport } from './routes/track/$token'
import { Route as ApiPrinterAckRouteImport } from './routes/api/printer/ack'
import { Route as ApiPrinterQueueRouteImport } from './routes/api/printer/queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const SurMesureRoute = SurMesureRouteImport.update({
  id: '/sur-mesure',
  path: '/sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/admin/stocks',
  path: '/admin/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieWebhookRoute = ApiMollieWebhookRouteImport.update({
  id: '/api/mollie-webhook',
  path: '/api/mollie-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order/success',
  path: '/order/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrinterAckRoute = ApiPrinterAckRouteImport.update({
  id: '/api/printer/ack',
  path: '/api/printer/ack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrinterQueueRoute = ApiPrinterQueueRouteImport.update({
  id: '/api/printer/queue',
  path: '/api/printer/queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/recrutement': typeof RecrutementRoute
  '/sur-mesure': typeof SurMesureRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/api/mollie-webhook': typeof ApiMollieWebhookRoute
  '/api/orders': typeof ApiOrdersRoute
  '/order/success': typeof OrderSuccessRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/track/$token': typeof TrackTokenRoute
  '/pos/': typeof PosIndexRoute
  '/api/printer/ack': typeof ApiPrinterAckRoute
  '/api/printer/queue': typeof ApiPrinterQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/recrutement': typeof RecrutementRoute
  '/sur-mesure': typeof SurMesureRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/api/mollie-webhook': typeof ApiMollieWebhookRoute
  '/api/orders': typeof ApiOrdersRoute
  '/order/success': typeof OrderSuccessRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/track/$token': typeof TrackTokenRoute
  '/pos': typeof PosIndexRoute
  '/api/printer/ack': typeof ApiPrinterAckRoute
  '/api/printer/queue': typeof ApiPrinterQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/recrutement': typeof RecrutementRoute
  '/sur-mesure': typeof SurMesureRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/api/mollie-webhook': typeof ApiMollieWebhookRoute
  '/api/orders': typeof ApiOrdersRoute
  '/order/success': typeof OrderSuccessRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/track/$token': typeof TrackTokenRoute
  '/pos/': typeof PosIndexRoute
  '/api/printer/ack': typeof ApiPrinterAckRoute
  '/api/printer/queue': typeof ApiPrinterQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/commander'
    | '/contact'
    | '/recrutement'
    | '/sur-mesure'
    | '/admin/stocks'
    | '/api/mollie-webhook'
    | '/api/orders'
    | '/order/success'
    | '/product/$productId'
    | '/track/$token'
    | '/pos/'
    | '/api/printer/ack'
    | '/api/printer/queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/commander'
    | '/contact'
    | '/recrutement'
    | '/sur-mesure'
    | '/admin/stocks'
    | '/api/mollie-webhook'
    | '/api/orders'
    | '/order/success'
    | '/product/$productId'
    | '/track/$token'
    | '/pos'
    | '/api/printer/ack'
    | '/api/printer/queue'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/commander'
    | '/contact'
    | '/recrutement'
    | '/sur-mesure'
    | '/admin/stocks'
    | '/api/mollie-webhook'
    | '/api/orders'
    | '/order/success'
    | '/product/$productId'
    | '/track/$token'
    | '/pos/'
    | '/api/printer/ack'
    | '/api/printer/queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  CommanderRoute: typeof CommanderRoute
  ContactRoute: typeof ContactRoute
  RecrutementRoute: typeof RecrutementRoute
  SurMesureRoute: typeof SurMesureRoute
  AdminStocksRoute: typeof AdminStocksRoute
  ApiMollieWebhookRoute: typeof ApiMollieWebhookRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  TrackTokenRoute: typeof TrackTokenRoute
  PosIndexRoute: typeof PosIndexRoute
  ApiPrinterAckRoute: typeof ApiPrinterAckRoute
  ApiPrinterQueueRoute: typeof ApiPrinterQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sur-mesure': {
      id: '/sur-mesure'
      path: '/sur-mesure'
      fullPath: '/sur-mesure'
      preLoaderRoute: typeof SurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stocks': {
      id: '/admin/stocks'
      path: '/admin/stocks'
      fullPath: '/admin/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie-webhook': {
      id: '/api/mollie-webhook'
      path: '/api/mollie-webhook'
      fullPath: '/api/mollie-webhook'
      preLoaderRoute: typeof ApiMollieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/success': {
      id: '/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printer/ack': {
      id: '/api/printer/ack'
      path: '/api/printer/ack'
      fullPath: '/api/printer/ack'
      preLoaderRoute: typeof ApiPrinterAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printer/queue': {
      id: '/api/printer/queue'
      path: '/api/printer/queue'
      fullPath: '/api/printer/queue'
      preLoaderRoute: typeof ApiPrinterQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  CommanderRoute: CommanderRoute,
  ContactRoute: ContactRoute,
  RecrutementRoute: RecrutementRoute,
  SurMesureRoute: SurMesureRoute,
  AdminStocksRoute: AdminStocksRoute,
  ApiMollieWebhookRoute: ApiMollieWebhookRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  TrackTokenRoute: TrackTokenRoute,
  PosIndexRoute: PosIndexRoute,
  ApiPrinterAckRoute: ApiPrinterAckRoute,
  ApiPrinterQueueRoute: ApiPrinterQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
